export const mapTable = {
  subjectMap:{
    full_name_zhtw:'測試標的',
  },
  companyProfileMap: {
    stock_code: "股票代號",
    full_name_zhtw: "公司全名",
    short_name_zhtw: "公司簡稱",
    gui_no: "統一編號",
    address_zhtw: "地址",
    phone: "電話",
    fax: "傳真",
    website: "網站",
    email: "電子郵件",
    industry_main: "主要產業",
    industry_sub: "次要產業",
    industry_national: "國家產業",
    ceo: "董事長", 
    capital: "資本額",
    employee_count: "員工數",
    founded_date: "成立日期",
    business_scope: "營業範圍",
    accountant_firm: "會計師事務所",
    accountants: "會計師",
    board_shareholding_ratio: "董事持股比例",
    board_pledge_ratio: "董事質押比例",
    listed_market: "上市櫃市場",
    par_value: "面額",
    ipo_date: "上市日期",
    avg_60d_price: "60日平均價格",
    avg_60d_volume: "60日平均成交量"
  },
  balanceSheetMap: {
    year: "年度",
    quarter: "季度",
    retained_earnings: "保留盈餘合計",
    other_accounts_receivable: "其他應收帳款淨額",
    other_current_assets: "其他流動資產合計",
    inventory: "存貨",
    accounts_receivable: "應收帳款淨額",
    total_equity: "權益總額",
    current_liabilities: "流動負債合計",
    current_assets: "流動資產合計",
    cash: "現金及約當現金",
    capital_stock: "股本合計",
    total_liabilities_and_equity: "負債及權益總計",
    capital_reserve: "資本公積合計",
    total_assets: "資產總額",
    non_current_liabilities: "非流動負債合計",
    non_current_assets: "非流動資產合計"
  },
  financialRatiosMap:{
    year:"年",
    gui_no:"統一編號",
    average_collection_period: "平均收現日數",
    total_asset_turnover: "總資產週轉率(次)",
    DECIMAL: "權益報酬率(%)",
    average_days_sales_outstanding: "平均銷貨日數",
    net_profit_margin: "純益率(%)",
    debt_to_asset_ratio: "負債佔資產比率(%)",
    pre_tax_profit_to_capital_ratio: "稅前純益佔實收資本比率(%)",
    long_term_capital_to_fixed_assets_ratio: "長期資金佔不動產、廠房及設備比率(%)",
    current_ratio: "流動比率(%)",
    interest_coverage_ratio: "利息保障倍數(%)",
    roa: "資產報酬率(%)",
    cash_reinvestment_ratio: "現金再投資比率(%)",
    cash_adequacy_ratio: "現金流量允當比率(%)",
    quick_ratio: "速動比率(%)",
    accounts_receivable_turnover: "應收款項週轉率(次)",
    fixed_assets_turnover: "不動產、廠房及設備週轉率(次)",
    inventory_turnover: "存貨週轉率(次)",
    cash_flow_ratio: "現金流量比率(%)",
    eps: "每股盈餘(元)"
  },
};